### ISSUE TITLE
Action is broken after Tuist 4 release

### ISSUE THREAD

**Issue by fedulvtubudul** [tuist/tuist-action#14]
Yesterday after Tuist v4 release we've encountered our GitHubActions-based CI was broken. We rely on Tuist GHA action for project generation:

```yaml
      - name: Generate project via Tuist
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'generate'
          arguments: ''
```

which fails with next error:

```
Run tuist/tuist-action@0.13.0
  with:
    command: generate
  env:
    FASTLANE_SKIP_UPDATE_CHECK: true
    PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools
Error: Cannot read properties of undefined (reading 'browser_download_url')
```

Please update `tuist/tuist-action` or provide users with other solution for this, as it becomes critical having CI totally broken.
